@startuml
title Диаграмма последовательности взаимодействия компонентов системы

actor "Спортсмен" as Athlete

participant "Клиентский интерфейс" as UI
participant "Серверная часть\n(API-сервис)" as API
database "Хранилище данных\n(PostgreSQL)" as DB


== Просмотр и выполнение тренировки спортсменом ==

Athlete -> UI: Открывает назначенную тренировку
UI -> API: Запросить тренировку спортсмена

activate API
API -> DB: Получить тренировку и список заданий спортсмена
activate DB
DB --> API: Данные тренировки, упражнения и задания
deactivate DB

API -> API: Проверить доступ спортсмена\nк запрошенной тренировке
API --> UI: Передать список заданий
deactivate API

UI --> Athlete: Отобразить тренировку и упражнения

Athlete -> UI: Вводит результат выполнения\nпопытки и успешные попытки
UI -> API: Передать результат выполнения задания

activate API
API -> API: Проверить корректность результата
API -> API: Проверить, что задание принадлежит спортсмену

alt Результат корректен
    API -> DB: Сохранить фактические попытки,\nуспешные попытки и статус задания
    activate DB
    DB --> API: Результат сохранен
    deactivate DB

    API --> UI: Подтвердить сохранение результата
    UI --> Athlete: Показать обновленный статус задания
else Ошибка проверки
    API --> UI: Сообщение об ошибке
    UI --> Athlete: Показать ошибку ввода результата
end

deactivate API


@enduml