@startuml
title Диаграмма последовательности взаимодействия компонентов системы

actor "Тренер" as Coach

participant "Клиентский интерфейс" as UI
participant "Серверная часть\n(API-сервис)" as API
database "Хранилище данных\n(PostgreSQL)" as DB


== Просмотр результатов и аналитики тренером ==

Coach -> UI: Открывает историю или аналитику
Coach -> UI: Выбирает период, группу,\nспортсмена или упражнение
UI -> API: Запросить аналитические данные

activate API
API -> API: Проверить права тренера\nна выбранные данные

API -> DB: Получить результаты тренировок\nпо заданным параметрам
activate DB
DB --> API: Сведения о тренировках,\nзаданиях и результатах
deactivate DB

API -> API: Агрегировать данные
API -> API: Рассчитать показатели результативности,\nдинамику и статистику

API --> UI: Передать показатели, таблицы и графики
deactivate API

UI --> Coach: Отобразить историю и аналитику

@enduml