@startuml

abstract class Пользователь {
  + id: int
  + имя: string
  - дата рождения: date
  + войти()
}

class Тренер {
  
}

class Спортсмен {

}

class Тренировка {
  + дата: date
}

class Попытка {
  
}

Пользователь <|-- Тренер
Пользователь <|-- Спортсмен

class Упражнение {
  + название: string
  + описание: string
  + создатьКопию()
}

class Позиция {
  + координаты: string
  + типШара: string
}

class Группа {
  + название: string
}

Группа o-- Спортсмен : состоит из
Упражнение *-- Позиция : содержит
Тренер "1" -- "0..*" Спортсмен : тренирует


@enduml