@startuml
title Диаграмма 1: Пользователи и группы

abstract class Пользователь {
  +id: bigint
  +email: varchar
  +password_hash: varchar
  +фамилия: varchar
  +имя: varchar
  +отчество: varchar
  +дата_рождения: date
  +создан: timestamptz
  +обновлен: timestamptz
  +удален: timestamptz?
}

class Тренер {
}

class Спортсмен {
}

class Группа {
  +id: bigint
  +название: varchar
  +тренер_id: bigint
  +описание: text?
  +создан: timestamptz
  +обновлен: timestamptz
  +удален: timestamptz?
}


class Посещаемость {
  +id: bigint
  +дата: date
  +статус: enum {присутствовал, отсутствовал, опоздал}
  +причина: text?
  +создан: timestamptz
}

' Наследование
Пользователь <|-- Тренер
Пользователь <|-- Спортсмен

' Связи групп и пользователей
Тренер "1" -- "0..*" Группа  
Группа "1" o-- "0..*" Спортсмен  


' Посещаемость
Спортсмен "1" -- "0..*" Посещаемость  

@enduml