@startuml
left to right direction

skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BorderColor Black
}

actor "Администратор" as admin

rectangle "Электронный дневник бильярдиста" {
  package "Пользователи" {
    usecase "Создать тренера" as UC_ADMIN_CREATE_COACH
    usecase "Просмотреть пользователей" as UC_ADMIN_VIEW_USERS
    usecase "Редактировать пользователя" as UC_ADMIN_EDIT_USER
  }

  package "Упражнения" {
    usecase "Просмотреть библиотеку упражнений" as UC_ADMIN_VIEW_EXERCISES
    usecase "Редактировать упражнение" as UC_ADMIN_EDIT_EXERCISE
  }
}

admin --> UC_ADMIN_CREATE_COACH
admin --> UC_ADMIN_VIEW_USERS
admin --> UC_ADMIN_EDIT_USER
admin --> UC_ADMIN_VIEW_EXERCISES
admin --> UC_ADMIN_EDIT_EXERCISE

@enduml
