@startuml
left to right direction

skinparam shadowing false
skinparam usecase {
  BackgroundColor White
  BorderColor Black
  FontSize 12
}
skinparam actor {
  BorderColor Black
}

actor "Спортсмен" as athlete

rectangle "Электронный дневник бильярдиста" {
  usecase "Просматривать\nназначенные тренировки" as UC_VIEW_TRAININGS
  usecase "Видеть назначенные\nупражнения" as UC_VIEW_EXERCISES
  usecase "Фиксировать\nрезультаты выполнения" as UC_RECORD_RESULTS
  usecase "Просматривать\nисторию тренировок" as UC_VIEW_HISTORY
  usecase "Получать обратную\nсвязь тренера" as UC_VIEW_FEEDBACK
}

athlete --> UC_VIEW_TRAININGS
athlete --> UC_VIEW_EXERCISES
athlete --> UC_RECORD_RESULTS
athlete --> UC_VIEW_HISTORY
athlete --> UC_VIEW_FEEDBACK

@enduml
