@startuml
left to right direction

actor "Тренер" as Coach

rectangle "Система дневника тренировок" {
  usecase "Управлять спортсменами" as UC_CreateAthlete
  usecase "Создать упражнение" as UC_CreateExercise
  usecase "Назначать тренировку" as UC_PlanTraining
  usecase "Назначать задания" as UC_AssignTasks
  usecase "Просматривать результаты" as UC_ViewResults
  usecase "Просматривать аналитику" as UC_ViewAnalytics
}

Coach -- UC_CreateAthlete
Coach -- UC_CreateExercise
Coach -- UC_PlanTraining
Coach -- UC_AssignTasks
Coach -- UC_ViewResults
Coach -- UC_ViewAnalytics

@enduml
