@startuml
left to right direction
actor "Тренер" as coach
rectangle "Электронный дневник бильярдиста" {
  usecase "Зафиксировать посещаемость тренировки" as UC1_3
  usecase "Создать упражнение в визуальном редакторе" as UC2_1
  usecase "Назначить упражнение спортсмену" as UC3_1
  usecase "Просматривать результаты выполнения упражнений" as UC4_3
  usecase "Видеть статистику по спортсмену" as UC5_1
  usecase "Добавлять комментарии к тренировкам" as UC6_1
}

coach --> UC1_3
coach --> UC2_1
coach --> UC3_1
coach --> UC4_3
coach --> UC5_1
coach --> UC6_1
@enduml