@startuml

entity position {
  id : SERIAL <<PK>>
  --
  layout : JSONB <<NOT NULL>>
  power : DOUBLE PRECISION
  created_at : TIMESTAMP <<DEFAULT now()>>
  updated_at : TIMESTAMP <<DEFAULT now()>>
}

@enduml